const sidcCodes = [
  { name: 'Unit', value: 'U-----' },
  { name: 'Combat', value: 'UC----' },
  { name: 'Air Defense', value: 'UCD---' },
  { name: 'Short Range Air Defense', value: 'UCDS--' },
  { name: 'Chaparral', value: 'UCDSC-' },
  { name: 'Stinger', value: 'UCDSS-' },
  { name: 'Vulcan', value: 'UCDSV-' },
  { name: 'Air Defense Missile', value: 'UCDM--' },
  { name: 'Light Air Defense Missile', value: 'UCDML-' },
  { name: 'Air Defense Missile Motorized (Avenger)', value: 'UCDMLA' },
  { name: 'Medium Air Defense Missile', value: 'UCDMM-' },
  { name: 'Heavy Air Defense Missile', value: 'UCDMH-' },
  { name: 'H/MAD', value: 'UCDH--' },
  { name: 'Hawk', value: 'UCDHH-' },
  { name: 'Patriot', value: 'UCDHP-' },
  { name: 'Gun Unit', value: 'UCDG--' },
  { name: 'Composite', value: 'UCDC--' },
  { name: 'Targeting Unit', value: 'UCDT--' },
  { name: 'Theater Missile Defense Unit', value: 'UCDO--' },
  { name: 'Armor', value: 'UCA---' },
  { name: 'Armor Track Airborne', value: 'UCATA-'},
  { name: 'Armor Track Amphibious', value: 'UCATW-'},
  { name: 'Armor Track Amphibious Recovery', value: 'UCATWR'},
  { name: 'Armor Track, Light', value: 'UCATL-'},
  { name: 'Armor Track, Medium', value: 'UCATM-'},
  { name: 'Armor Track, Heavy', value: 'UCATH-'},
  { name: 'Armor Track, Recovery', value: 'UCATR-'},
  { name: 'Armor, Wheeled', value: 'UCAW--'},
  { name: 'Armor, Wheeled Air Assault', value: 'UCAWS-'},
  { name: 'Armor, Wheeled Airborne', value: 'UCAWA-'},
  { name: 'Armor, Wheeled Amphibious', value: 'UCAWW-'},
  { name: 'Armor, Wheeled Amphibious Recovery', value: 'UCAWWR'},
  { name: 'Armor, Wheeled Light', value: 'UCAWL-'},
  { name: 'Armor, Wheeled Medium', value: 'UCAWM-'},
  { name: 'Armor, Wheeled Heavy', value: 'UCAWH-'},
  { name: 'Armor, Wheeled Recovery', value: 'UCAWR-'},
  { name: 'Anti-Armor', value: 'UCAA--'},
  { name: 'Light Anti-Armor', value: 'UCAAL-'},
  
]

export { sidcCodes }